---
title: "Regression Activity - Pt. 2: Regression Modeling"
crossref:
  lst-title: "🎯 Checkpoint 5."
  lst-labels: alpha a
format: live-html
sidebar: lesson-3
---
:::{.ltblue-container}
**Checkpoints on this Page:**

- [**Checkpoint 5.a:** Putting Data in Lists](#lst-lists)
- [**Checkpoint 5.b:** Scatterplots in Python](#lst-scatterplots)
- [**Checkpoint 5.c:** Regression in Python](#lst-regression)
- [**Checkpoint 5.d:** Regression Equation in Python](#lst-regression-equation)
- [**Checkpoint 5.e:** Plotting Regression Line in Python](#lst-regression-line-python)
- [**Checkpoint 5.f:** Transferring Regression Line to Paper](#lst-regression-line-paper)
:::

## Regression Modeling

```{=html}
<br>
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
  <iframe 
    src="https://www.youtube.com/embed/e18KM681cmg?start=8&end=74" 
    frameborder="0" 
    allowfullscreen
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;">
  </iframe>
</div>
<br>
```

There are a few ways to create a line of best fit, but we will use Python to run a linear regression for us! It will generate our line of best fit.

:::{#lst-lists}

:::{.dkorange-container}
Replace the `??` placeholder with the color values and nitrate concentrations from the RBG activity and scatterplot!

**IMPORTANT:** The color values and nitrate concentrations must be in the exact same order.

Click the ▶️ Run Code button to run the block and store your data.
:::

### Storing Your Data

```{pyodide}
#| include: false
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def process_data(color_data, nitrate_ppm):
    color_data = np.array(color_data)
    nitrate_ppm = np.array(nitrate_ppm)
    return color_data, nitrate_ppm

def process_df(color_data, nitrate_ppm):
    df = pd.DataFrame({
        "color_data": color_data,
        "nitrate_ppm": nitrate_ppm
    })
    return df

def linear_regression(x, y):
    slope, intercept = np.polyfit(x, y, 1)
    return slope, intercept
```


```{pyodide}
#| persist: true
#| completion: false
color_data = [??, ??, ??, ??, ??, ??, ??, ??]
nitrate_ppm = [??, ??, ??, ??, ??, ??, ??, ??]

print(color_data)
print(nitrate_ppm)

# Do not change the code below ------------------------------------
color_data, nitrate_ppm = process_data(color_data, nitrate_ppm)
df = process_df(color_data, nitrate_ppm)
```

Storing your team's data in a list!
:::

### Recreating Your Team's Scatterplot

:::{#lst-scatterplots}
:::{.dkorange-container}
Replace the `??` placeholders with the x variable (`color_data`) in the first blank and the y variable (`nitrate_ppm`) in the second.

Click the ▶️ Run Code button to create a scatterplot that should match your group's paper plot.
:::

```{pyodide}
#| persist: true
#| completion: false
plt.figure(figsize=(6, 5))
plt.scatter(df["??"], df["??"], s=60, color="black")
plt.title("Nitrate vs. Color")
plt.xlabel("Color")
plt.ylabel("Nitrate (ppm)")
plt.tight_layout()
plt.show()
```
Scatterplots in Python!
:::

### Running the Linear Regression

:::{#lst-regression}
:::{.dkorange-container}
Replace the `??` placeholders with the x variable (`color_data`) in the first blank and the y variable (`nitrate_ppm`) in the second blank.

Click the ▶️ Run Code button to run the block and generate the equation for the line of best fit.
:::

```{pyodide}
#| persist: true
#| completion: false
slope, intercept = linear_regression(??,??)

print("slope (m):",slope)
print("intercept (b):",intercept)
```

Running a regression in Python
:::

**NOTE:** The linear regression produces the equation for the line of best fit. After we know the equation, we can graph it.

Remember ***y = mx + b***?  
We can just substitute!

:::{#lst-regression-equation}
:::{.dkorange-container}
No code edits needed!

Click the ▶️ Run Code button to see the slope-intercept equation of your regression line.
:::

```{pyodide}
print(f"y = {slope:.2f}x + {intercept:.2f}")
```

Printing the Regression Equation
:::

### Plotting the Regression Line

:::{#lst-plotting-line-python}
:::{.dkorange-container}
No code edits needed!

Click the ▶️ Run Code button to plot the scatterplot with the regression line included.
:::

```{pyodide}
nitrate_pred = slope * color_data + intercept

plt.figure(figsize=(6, 5))
plt.scatter(color_data, nitrate_ppm, s=60, color="black")
plt.plot(color_data, nitrate_pred, color="black", linewidth=1)
plt.title("Nitrate Concentration vs. Color")
plt.xlabel("Color")
plt.ylabel("Nitrate Concentration (ppm)")
plt.text(
    min(color_data),
    max(nitrate_ppm),
    f"y = {slope:.2f}x + {intercept:.2f}\n",
    ha="left",
    fontsize=10,
    color="gray"
)
plt.tight_layout()
plt.show()
```

Plotting regression line in Python
:::

## Activity - Draw your line of best fit on your group's scatterplot

:::{#lst-plotting-line-paper}
:::{.gray-container}
**Materials Needed:**  
- Poster Markers  
- Scatterplot  
- Yardstick  
:::

Using the exact positioning the line of best fit python generated, copy that line onto your group's scatterplot. When finished, bring your group's plot to the front of the class.

Plotting regression line on paper
:::