---
title: "Color Activity"
crossref:
  lst-title: "🎯 Checkpoint 6."
  lst-labels: alpha a
format: live-html
sidebar: lesson-2
---

:::{.ltblue-container}
**Checkpoints on this Page:**

- [**Checkpoint 6.a:** Pixels & RGB](#lst-RGBPixels)
:::

## Understanding RGB
To understand how Smokey Buoy uses color to monitor water quality, we need to understand how computers *see* color. Computers aren't like us—they don't have eyes. Instead, computers understand color through numbers.

When a computer displays or processes an image, that image is really a combination of millions of little squares called pixels, and each of these pixels has a value for [Red]{style="color: #ff0000;"} (R), [Green]{style="color: #00ff00;"} (G), and [Blue]{style="color: #0000ff;"} (B). The color of each pixel is a combination of these three values.

Let's take a look at how this works!

<hr>

### Pixels and RGB Values

:::{#lst-RGBPixels}

```{pyodide}
#| include: false

# Fake block to make checkpoint work
```
Exploring pixels and RGB Values
:::

:::{.gray-container}
**Materials Needed:**  

- [APPLET](../RGB-Applet-1.html){target="_blank" rel="noopener"}
    - This will open in a new tab. 
    - You may need to grant access to your camera for it to work.
    - Apple, Orange, Lime (from previous activity)
- Handout
- Pencil
:::

Use the applet and follow the instructions on the handout, which are also listed below.

1. The applet starts with "What Humans See" selected. Hold the apple up to the camera. Notice it captures its likeness?

2. Change the mode to "What Computers See". It will default to the Red channel first.

3. Focus on an area at the center of the apple and record the value for R.

4. Use the dropdown menu to change the channel to G. Look at the same area (or as close to possible) on the apple, record the value for G.

5. Repeat this process for the B channel.

6. Repeat this process for the orange, lime, and each of the purple cards.

