---
title: "Water Quality and Summary Statistics"
crossref:
  lst-title: "🎯 Checkpoint"
format: live-html
sidebar: lesson-2
---

::: {.gray-container}

**Lesson Objective:** In this lesson, you will learn how to use classification and Python to help computers recognize pH strips from water samples and understand how color (RGB) can be used to monitor water quality.

**Materials Needed:**  
- Your computer  
- A web browser (Chrome, Firefox, or Safari)  
- Purple Image Card
:::

:::{.ltblue-container}
**Checkpoints on this Page:**

- [**Checkpoint 1:** Get to Know the Buoy's Motorized Unit](#lst-motorunit)
- [**Checkpoint 2:** Get to Know the Buoy's Camera System](#lst-camera)
- [**Checkpoint 3:** Get to Know the Buoy's Radio Communication](#lst-telemetry)
- [**Checkpoint 4:** Get to Know the Buoy's Solar Power](#lst-solar)

:::

## 🔬💧 Welcome Back, Scientists!  

** INSERT QUESTIONS FROM EXIT TICKET AND MODULE 1 QUICK REVIEW/FEEDBACK HERE **

**Still stuck?** WHAT CAN THEY DO IF THEY"RE STILL STUCK?

## 💻 Meet the Buoy!

HydroBot is an open-source floating buoy that checks nutrients and pollutants in moving freshwater like streams and rivers. It mixes robot parts, smart computer learning right on the buoy, and far-reaching wireless signals to watch specific spots and meet community needs. The system has four main parts: a motorized unit that uses paper test strips which change color in water; a built-in camera system to analyze those strips on the spot; a long-range radio to send data to online dashboards; and a solar-powered floating case to keep it running (paper citation).

### Motorized Unit
(info here)

(picture here)

:::{#lst-motorunit}

:::{.dkorange-container}
Quick Think Pair Share: How does the motorized roller help the buoy test water without someone constantly checking it? Share one pro or con with your neighbor. 

### On Board Camera System
(info here)

(Picture here)

:::{#lst-camera}

:::{.dkorange-container}
Poll Question: What do you think the camera "sees" to know when a test strip is ready? Thumbs up if color, thumbs down if shape. Discuss why!

### Radio Communication
(info here)

(Picture here)

:::{#lst-telemetry}

:::{.dkorange-container}
Facilitator prompt: Imagine the buoy is 2 miles from the lab - how does the radio send data without WiFi? What might stop the signal?

### Solar Power
(info here)

(image here)

:::{#lst-solar}

:::{.dkorange-container}
Quick guess: How man days could the buoy run on solar power alone during a rainy week? Thumbs up for 1-2 days, to the side for 1-2 weeks, down for a month or more. Why do you think so?

## 🚀 Ready to Dive In?

Click "Intro to Classification" in the left-hand menu to continue your journey as a water quality scientist!

Remember: **Everyone starts as a beginner.** If something doesn't make sense, that's normal! Try it again, experiment, and ask questions.

Let's go! 🚀