---
title: "How Does It Work?"
crossref:
  lst-title: "🎯 Checkpoint 5."
  lst-labels: alpha a
format: live-html
sidebar: lesson-2
---

:::{.ltblue-container}
**Checkpoints on this Page:**

- [**Checkpoint 5.a:** Neural Network Layers](#lst-nnlayers)
:::

## How Does Your Model Work?

Under the hood of your model and most other image classification models is something called a **Convolutional Neural Net (CNN)**. As you have already done, we train CNNs to recognize pattern in images. Watch the clip below to learn more about how the CNN works. Note that the video discussed some of the mathematics behind CNNs, but don't worry if you don't understand everything. Prioritize understanding the big picture, as the video clips moves quickly.
<br>

<b> Clip 1 </b>
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
  <iframe 
    src="https://www.youtube.com/embed/oV3ZY6tJiA0?start=197&end=234" 
    frameborder="0" 
    allowfullscreen
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;">
  </iframe>
</div>
<br>

<br>
<b> Clip 2 </b>
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
  <iframe 
    src="https://www.youtube.com/embed/oV3ZY6tJiA0?start=351&end=540" 
    frameborder="0" 
    allowfullscreen
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;">
  </iframe>
</div>
<br>

:::{#lst-nnlayers}

```{pyodide}
#| include: false

# Fake block to make checkpoint work
```
Compare and contrast the input layer, the hidden layers, and the output layer. What function do they each have in a neural net?
:::

The example in the video focuses on classifying objects in grayscale photos, but CNNs can also handle color. However, computers "see" color differently than humans.

## Understanding How Computers See Color

Computers do not prize the beauty of a painting or the wonder of an emotionally stirring photograph. Instead, they understand these images through numbers.
<br><br>
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
  <iframe 
    src="https://www.youtube.com/embed/oV3ZY6tJiA0?start=250&end=297" 
    frameborder="0" 
    allowfullscreen
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;">
  </iframe>
</div>
<br>
 ** Note that the red, green, and blue values in this video are given as decimals because some math has been applied to them. The original values are whole numbers between 0 and 255, as we'll see on the next page.